language: go
sudo: required
services:
  - docker
go:
  - 1.6
env:
  - GOARCH=amd64 DOCKER_VERSION=1.11.2-0
  - GOARCH=amd64 DOCKER_VERSION=1.12.0~rc3-0
before_install:
  - sudo sh -c 'echo "deb https://apt.dockerproject.org/repo ubuntu-precise main"          > /etc/apt/sources.list.d/docker.list'
  - sudo sh -c 'echo "deb https://apt.dockerproject.org/repo ubuntu-precise experimental" >> /etc/apt/sources.list.d/docker.list'
  - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - sudo apt-get update
  - sudo apt-get -qqy -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install docker-engine=${DOCKER_VERSION}~precise
script:
  - make test
  - make
  - mkdir -p /home/travis/gopath/bin 
  - cp rocker /home/travis/gopath/bin/
  - make test_integration
